server:
	gcc -lnsl -lresolv tcpServer.c -o ownTcpServer
	gcc -lnsl -lresolv udpServer.c -o ownUdpServer

client:
	gcc -lnsl -lresolv tcpClient.c -o ownTcpClient
	gcc -lnsl -lresolv UDPClientAufg6.c -o ownUdpClient
